Repository kloudsoft91/mushroom_db_app, pull requests merged in 2023-10, with the labels that each got.

#62 Fix toxic label
  components/ResultCards.vue
Labels: bug

#71 New readme
  README.md
  assets/images/adminui_main.png
  assets/images/ui_main_filters.png
  assets/images/ui_main_search.png
Labels: documentation

#70 Detail url filters
  assets/css/tailwind.css
  components/ResultCards.vue
  components/images/irregular.png
  data/sampledata.js
  index.test.js
  nuxt.config.ts
  package.json
  pages/index.vue
  pages/mushroom-detail.vue
  pages/mushroom-detail/[id].vue
Labels: enhancement
